# Generated by Django 2.1.5 on 2019-01-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('gps_x', models.DecimalField(decimal_places=7, max_digits=15)),
                ('gps_y', models.DecimalField(decimal_places=7, max_digits=15)),
                ('address', models.CharField(max_length=200)),
                ('student_discount', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
    ]
