# Generated by Django 2.2.dev20190110235441 on 2019-01-18 01:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 1, 33, 23, 841000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='buisness',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
